# Python runtime base image
FROM python:3.11

# Set working directory
WORKDIR /app

# Copy common folder
COPY common/ /app/common/

# Copy project files
COPY api/ /app/api/
COPY etl/analyzer/ /app/etl/analyzer/

# Install Python dependencies
COPY requirements.api.txt .
RUN pip install --no-cache-dir -r requirements.api.txt

# Set Python path to include common
ENV PYTHONPATH=/app

# Run gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "api.wsgi:app"]
